image: alpine/latest

packages:
  - nodejs
  - npm

git.sr.ht:
  enabled: true
  allow-refs:
    - refs/heads/*

secrets:
  - 34a7d712-4558-4943-a03d-c8057965f23c # SSH for srht-builds
  - 62aca017-2dfb-4fb1-aecf-b1c3d1e4d4a0 # SSH for pushing to mirrors
  - 9e7fe4d8-c333-4116-97e7-c29e68409a21 # Cloudflare API token

environment:
  CLOUDFLARE_ACCOUNT_ID: cc1f9251f98d1dab3451b99675c70166
  NODE_OPTIONS: --max-old-space-size=4096

triggers:
  - action: email
    condition: failure
    to: whacking_conflict869@simplelogin.com

tasks:
  - install_pnpm: |
      sudo npm i -g pnpm
  - setup: |
      cd suttacentral-ssr
      pnpm i
  - build: |
      cd suttacentral-ssr
      pnpm i
      pnpm run build
  - deploy: |
      cd suttacentral-ssr
      export CLOUDFLARE_API_TOKEN=$(cat ~/.cloudflare)
      BRANCH="${GIT_REF#refs/heads/}"
      npx wrangler pages deploy dist --project-name=suttacentral-ssr --branch="$BRANCH"
  - mirror: |
      cd suttacentral-ssr
      BRANCH="${GIT_REF#refs/heads/}"
      if [ "$BRANCH" = "main" ]; then
        GIT_SSH_COMMAND="ssh -i ~/.ssh/62aca017-2dfb-4fb1-aecf-b1c3d1e4d4a0 -o StrictHostKeyChecking=no" git push --mirror git@codeberg.org:benmneb/suttacentral-ssr.git
        GIT_SSH_COMMAND="ssh -i ~/.ssh/62aca017-2dfb-4fb1-aecf-b1c3d1e4d4a0 -o StrictHostKeyChecking=no" git push --mirror git@github.com:benmneb/suttacentral-ssr.git
      fi
