/**
 * UID segment abbreviations and their expansions, from the SuttaCentral API:
 * https://suttacentral.net/api/expansion
 *
 * Used by `expandUid()` to turn hyphenated UIDs (e.g. 'pli-tv-bi-vb-pc4')
 * into readable strings (e.g. 'Pli Tv Bi Vb Pc 4').
 */
export const expansionData: Record<string, [string, string]> = {
  abhidhamma: ['Abhidhamma', 'Abhidhamma'],
  acip: ['ACIP', 'Asian Classics Input Project'],
  an: ['AN', 'Aṅguttara Nikāya'],
  ap: ['Ap', 'Āpadāna'],
  arv: ['Arv', 'Arthaviniścaya'],
  as: ['As', 'Adhikaraṇasamatha'],
  asc: ['Asc', 'Abhisamācārika'],
  avs: ['Avs', 'Avadānaśataka'],
  ay: ['Ay', 'Aniyata'],
  ba: ['BA', 'Bhikkhu Adhyāya'],
  bf: ['Bf', 'Bajaur'],
  bi: ['Bi', 'Bhikkhunī'],
  bj: ['Bj', 'Buddhajayantītripiṭakagranthamālā 2501–2531 (1957–1989)'],
  'bj-a': [' Bj A', 'Buddhajayantītripiṭakagranthamālā Atthakathā)'],
  bu: ['Bu', 'Bhikkhu'],
  bv: ['Bv', 'Buddhavaṁsa'],
  'c-a': ['C-A', 'Chaṭṭhasaṅgīti Piṭakaṁ Atthakathā'],
  c1: ['C1', 'Chaṭṭhasaṅgīti Piṭakaṁ 2496–2499 (1952–1955)'],
  c2: ['C2', 'Chaṭṭhasaṅgīti Piṭakaṁ 2nd ed. 2500–2506 (1956–1962)'],
  c3: ['C3', 'Chaṭṭhasaṅgīti Piṭakaṁ (1997)'],
  cases: ['cases', 'cases'],
  cbeta: ['CBETA', 'Chinese Buddhist Electronic Text Association'],
  cha1: ['C1', 'Chaṭṭhasaṅgīti Piṭakaṁ 2496–2499 (1952–1955)'],
  cha2: ['C2', 'Chaṭṭhasaṅgīti Piṭakaṁ 2nd ed. 2500–2506 (1956–1962)'],
  cha3: ['C3', 'Chaṭṭhasaṅgīti Piṭakaṁ (1997)'],
  cnd: ['Cnd', 'Cūḷaniddesa'],
  conc: ['Conc.', 'Conclusion'],
  cp: ['Cp', 'Cariyāpiṭaka'],
  cps: ['Cps', 'Catuṣpariṣatsūtra'],
  d: ['D', 'Derge edition'],
  da: ['DA', 'Dīrghāgama'],
  ddb: ['DDB', 'Digital Dictionary of Buddhism'],
  de: ['De', 'German'],
  dg: ['Dg', 'Dharmaguptaka'],
  dh: ['DH', 'Dun Huang'],
  dhp: ['Dhp', 'Dhammapada'],
  divy: ['Divy', 'Divyāvadāna'],
  dk: ['Dk', 'Dharmaskandha'],
  dn: ['DN', 'Dīgha Nikāya'],
  dr: ['Dr', 'Dayyaraṭṭhassa Saṅgītitepiṭakaṁ'],
  ds: ['Ds', 'Dhammasaṅgaṇī'],
  dt: ['Dt', 'Dhātukathā'],
  du: ['Du', 'Dukkaṭa'],
  dy: ['Dy', 'Dhātukāya'],
  ea: ['EA', 'Ekottarikāgama (1st)'],
  'ea-2': ['EA2 [T 150A]', 'Ekottarikāgama (2nd)'],
  ed: ['ed', 'edited, editor, edition'],
  en: ['En', 'English'],
  es: ['Es', 'Spanish'],
  f: ['F', 'Fragment'],
  finot: ['Finot', 'Finot'],
  fr: ['Fr', 'French'],
  g: ['G', 'Gilgit'],
  g2dhp: ['G-2-Dhp', 'Gāndhārī Dharmapada British Library Fragment 16'],
  g3dhp: ['G-3-Dhp', 'Gāndhārī Dharmapada Split Collection Fragment 3'],
  gbm: ['GBM', 'Gilgit Buddhist Manuscripts'],
  gd: ['Gd', 'Garudhamma'],
  gdhp: ['G-Dhp', 'Gāndhārī Dharmapada'],
  gf: ['Gandh', 'Gāndhārī fragments'],
  gretil: [
    'GRETIL',
    'Göttingen Register of Electronic Texts in Indian Languages',
  ],
  hf: ['Hf', 'Hybrid Sanskrit fragment'],
  hsan: ['Hsan', 'Hybrid Sanskrit'],
  hv: ['Hv', 'Haimavata'],
  isi: ['Isibhās', 'Isibhāsiyāiṁ'],
  iti: ['Iti', 'Itivuttaka'],
  ja: ['Ja', 'Jātaka'],
  jp: ['Jp', 'Jnānaprasthāna'],
  ka: ['Ka', 'Kāśyapīya'],
  'ka-ma': ['Mr', 'Maramma Tipiṭaka 2541 (1997)'],
  kag: ['KA', 'Khuddakāgama'],
  kam: ['Kam', 'Kammavācā'],
  kd: ['Kd', 'Khandhaka'],
  kf: ['Khot', 'Khotanese fragments'],
  kg: ['Kg', 'Kangyur'],
  kho: ['Kho', 'Khotanese'],
  khv: ['Khv', 'Khuddakavatthu'],
  km: ['Km', 'Phratraipiṭakapāḷi 2501–2512 (1958–1969)'],
  kn: ['KN', 'Khuddaka Nikāya'],
  ko: ['Ko', 'Korean'],
  kp: ['Kp', 'Khuddakapāṭha'],
  ks: ['KS', 'Kindred Sayings'],
  kv: ['Kv', 'Kathāvatthu'],
  lal: ['Lal', 'Lalitavistara'],
  ll: ['ll', 'Parallels'],
  lo: ['Lo', 'Lokuttaravāda'],
  lzh: ['Lzh', 'Literary Chinese'],
  ma: ['MA', 'Madhyamāgama'],
  maku: [' Maku', 'Mahāmakurājāvidyālai 2466 (1923)'],
  mbh: ['Mbh', 'Mahābhārata'],
  mc: ['Mc', 'Mahācūḷātepiṭakaṁ'],
  mg: ['Mg', 'Mahāsaṅghika'],
  mh: ['Mh', 'Mahāsūtras'],
  mi: ['Mi', 'Mahīśāsaka'],
  mil: ['Mil', 'Milindapañha'],
  mkv: ['Mkv', 'Mahākarmavibhaṅga'],
  mn: ['MN', 'Majjhima Nikāya'],
  mnd: ['Mnd', 'Mahāniddesa'],
  mpt: ['Mpt', 'Mahāvyutpatti'],
  mr: ['Mr', 'Maramma Tipiṭaka 2541 (1997)'],
  ms: ['Ms', 'Mahasaṅgīti Tipiṭaka'],
  mu: ['Mu', 'Mūlasarvāstivāda'],
  mvu: ['Mvu', 'Mahāvastu'],
  my: ['My', 'Burmese'],
  nd: ['Nd', 'Niddesa'],
  ne: ['Ne', 'Nettipakaraṇa'],
  nidana: ['Nidana', 'Nidāna'],
  np: ['NP', 'Nissaggiya Pācittiya'],
  oa: ['OA', 'Other Āgama Sūtras'],
  om: ['OM', 'Other Mātikā'],
  'other-t': ['Other T', 'Other Taishō'],
  p: ['P', 'Page'],
  pa1: ['PTS 1', 'Pali Text Society 1st ed. 2424–2535 (1881–1992)'],
  pa2: ['PTS 2', 'Pali Text Society 2nd ed. 2517–2541 (1974–1998)'],
  patthana: ['Patthana', 'Paṭṭhāna'],
  pc: ['Pc', 'Pācittiya'],
  pd: ['Pd', 'Pāṭidesanīya'],
  pdhp: ['P-Dhp', 'Patna Dharmapada'],
  pe: ['Pe', 'Peṭakopadesa'],
  pf: ['PF', 'Prākrit fragments'],
  pgd: ['Pgd', 'Gāndhārī'],
  pj: ['Pj', 'Pārājika'],
  pk: ['Pk', 'Prakaraṇapada'],
  pli: ['Pli', 'Pāli'],
  pm: ['Pm', 'Pātimokkha'],
  pn: ['Pn', 'Pakiṇṇaka'],
  pp: ['Pp', 'Puggalapaññatti'],
  pra: ['Pra', 'Prākrit'],
  praj: ['Praj', 'Prajnaptiśāstra'],
  ps: ['Ps', 'Paṭisambhidāmagga'],
  'pts-a': ['PTS-A', 'Pali Text Society Atthakathā'],
  pts1: ['PTS 1', 'Pali Text Society 1st ed. 2424–2535 (1881–1992)'],
  pts2: ['PTS 2', 'Pali Text Society 2nd ed. 2517–2541 (1974–1998)'],
  pu: ['Pu', 'Puggalavāda'],
  pv: ['Pv', 'Petavatthu'],
  pvr: ['Pvr', 'Parivāra'],
  q: ['Q', 'Qianlong (Peking edition of Tibetan canon)'],
  qizil: ['Qizil', 'Qizil'],
  ru: ['Ru', 'Russian'],
  's-a': ['S-A', 'Syāmaraṭṭhassa Tepiṭakaṁ Atthakathā'],
  s1: ['S 1', 'Chulachomklao Pāḷi Tipiṭaka 2436 (1893)'],
  s2: ['S 2', 'Syāmaraṭṭhassa Tepiṭakaṁ 2469–2471 (1926–1928)'],
  s3: ['S 3', 'Syāmaraṭṭhassa Tepiṭakaṁ 2538 (1995)'],
  sa: ['SA', 'Saṁyuktāgama (1st)'],
  'sa-2': ['SA-2', 'Saṁyuktāgama (2nd)'],
  'sa-3': ['SA-3', 'Saṁyuktāgama (3rd)'],
  sab: ['Sab', 'Śāriputrābhidharma'],
  sag: ['Sag', 'Śarīrārthagāthā'],
  san: ['San', 'Sanskrit'],
  sarv: ['Sarv', 'Sarvāstivāda'],
  sb: ['Sb', 'Saṅghabhedavastu'],
  sbh: ['Sbh', 'Śrāvakabhūmi'],
  sc: ['SC', 'SuttaCentral'],
  sf: ['SF', 'Sanskrit Āgama Sūtras'],
  sg: ['Sg', 'Saṅgītiparyāya'],
  sht: ['SHT', 'SHT fragments'],
  si: ['Si', 'Sinhala Tipiṭaka 2501 (1957)'],
  sk: ['Sk', 'Sekhiya'],
  sm: ['Sm', 'Sikkhamānā'],
  sn: ['SN', 'Saṁyutta Nikāya'],
  snp: ['Snp', 'Sutta Nipāta'],
  spp: ['Spp', 'Śāriputraparipṛcchā'],
  ss: ['Ss', 'Saṅghādisesa'],
  sutta: ['Sutta', 'Suttas'],
  suy: ['Sūy', 'Sūyagadamgasuttam'],
  sya1: ['S 1', 'Chulachomklao Pāḷi Tipiṭaka 2436 (1893)'],
  'sya1-3': [
    'S 1–3',
    'Chulachomklao Pāḷi Tipiṭaka 2436 (1893),Syāmaraṭṭhassa Tepiṭakaṁ 2469–2471 (1926–1928) & 2538 (1995)',
  ],
  sya2: ['S 2', 'Syāmaraṭṭhassa Tepiṭakaṁ 2469–2471 (1926–1928)'],
  sya3: ['S 3', 'Syāmaraṭṭhassa Tepiṭakaṁ 2538 (1995)'],
  t: ['T', 'Taishō'],
  t1670a: ['T 1670 A', 'Nāgasena Bhikṣu Sūtra (1st)'],
  t1670b: ['T 1670 B', 'Nāgasena Bhikṣu Sūtra (2nd)'],
  tf: ['Tf', 'Turfan'],
  'tha-ap': ['Tha Ap', 'Therāpadāna'],
  thag: ['Thag', 'Theragāthā'],
  'thi-ap': ['Thi Ap', 'Therīapadāna'],
  thig: ['Thig', 'Therīgāthā'],
  tib: ['Tib', 'Tibetan'],
  tl: ['Tl', 'Thullaccaya'],
  tv: ['Tv', 'Theravāda'],
  ud: ['Ud', 'Udāna'],
  uf: ['Uigh', 'Uighur fragments'],
  uig: ['Uig', 'Uighur'],
  up: ['Up', 'Upāyikā'],
  upp: ['Upp', 'Upaliparipṛcchā'],
  utg: ['Utg', 'Uttargantha'],
  utt: ['Utt', 'Uttarādhyayanasūtra'],
  uv: ['Uv', 'Udānavarga'],
  uvs: ['UvS', 'Udānavarga de Subaši'],
  vagga: ['Vagga', 'Vagga'],
  vb: ['Vb', 'Vibhaṅga'],
  ve: ['VE', 'Vinaya Ekottara'],
  vi: ['Vi', 'Vietnamese'],
  vinaya: ['Vinaya', 'Vinaya'],
  vk: ['Vk', 'Vijnānakāya'],
  vns: ['Vns', 'Vinayanidānasūtra'],
  vol: ['Vol', 'Volume'],
  vs: ['VS', '(Vinaya) Saṁyutta'],
  vv: ['Vv', 'Vimānavatthu'],
  wp: ['WP', 'Wisdom Publications'],
  xct: ['Xct', 'Classical Tibetan'],
  ya: ['Ya', 'Yamaka'],
  ybs: ['Ybs', 'Yogācārabhūmi'],
  zh: ['Zh', 'Chinese'],
}
