/**
 * Rewrites the constants that are straight copies of a SuttaCentral API
 * response, so they dont have to be fetched on every page render.
 *
 * Overwrites, in full:
 *   src/constants/expansion.ts          expansionData
 *     <- /api/expansion, the uid abbreviations expandUid() reads
 *   src/constants/reference-editions.ts referenceEditions
 *     <- /api/pali_reference_edition, the names behind a reference tooltip
 *
 * Only for constants that are pure dumps. The hand-curated ones stay by hand:
 * AVAILABLE_LOOKUPS in lookup.ts is picked from what the web UI offers rather
 * than an endpoint, HANZI_VARIANTS and iso-codes.ts and edition.ts are ported
 * from .net's source with notes attached, and a generator would wipe those.
 *
 * Prints the keys added, removed and changed, and leaves a file alone if the
 * fetch fails or comes back empty, so a bad day at SC cant empty one out.
 *
 * Run: pnpm sync-api-constants
 * After running: review changes then commit.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { format, resolveConfig } from 'prettier'

const __dirname = dirname(fileURLToPath(import.meta.url))
const CONSTANTS_DIR = join(__dirname, '..', 'src', 'constants')

/** Keys only need quoting when they arent a plain identifier, eg 'bj-a' */
function key(k: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
}

/** `{ a: 'x', b: 'y' }` as the body of an object literal, one entry a line */
function entries(
  data: Record<string, unknown>,
  value: (v: any) => string
): string {
  return Object.keys(data)
    .sort()
    .map(k => `  ${key(k)}: ${value(data[k])},\n`)
    .join('')
}

const CONSTANTS = [
  {
    file: 'expansion.ts',
    url: 'https://suttacentral.net/api/expansion',
    // The api wraps the whole lot in a single-element array
    pick: (json: any) => json[0] as Record<string, [string, string]>,
    render: (data: Record<string, [string, string]>) =>
      `/**
 * UID segment abbreviations and their expansions, from the SuttaCentral API:
 * https://suttacentral.net/api/expansion
 *
 * Used by \`expandUid()\` to turn hyphenated UIDs (e.g. 'pli-tv-bi-vb-pc4')
 * into readable strings (e.g. 'Pli Tv Bi Vb Pc 4').
 *
 * Generated by \`pnpm sync-api-constants\`.
 */
export const expansionData: Record<string, [string, string]> = {
${entries(data, v => `[${v.map((s: string) => JSON.stringify(s)).join(', ')}]`)}}
`,
  },
  {
    file: 'reference-editions.ts',
    url: 'https://suttacentral.net/api/pali_reference_edition',
    pick: (json: any) =>
      Object.fromEntries(
        json.map((e: { edition_set: string; name: string }) => [
          e.edition_set,
          e.name,
        ])
      ) as Record<string, string>,
    render: (data: Record<string, string>) =>
      `/**
 * The printed editions a reference can point at, from the SuttaCentral API:
 * https://suttacentral.net/api/pali_reference_edition
 *
 * Only used for the tooltip on a reference link, so a reader hovering bj10.20
 * can see which edition it is. Vendored rather than fetched - it is a handful
 * of entries, and every text page would otherwise ask for it.
 *
 * Generated by \`pnpm sync-api-constants\`.
 */
export const referenceEditions: Record<string, string> = {
${entries(data, v => JSON.stringify(v))}}

// Longest first, so pts-vp-pli1.7 finds pts and not something shorter
const editionSets = Object.keys(referenceEditions).sort(
  (a, b) => b.length - a.length
)

/**
 * The edition a reference id belongs to, by its prefix, the way .net's
 * _getReferenceInfo walks the id from longest to shortest. Some systems have no
 * entry at all (nya, vns, vnp), and those just go without
 */
export function referenceEditionName(ref: string): string | undefined {
  const set = editionSets.find(s => ref.startsWith(s))
  return set ? referenceEditions[set] : undefined
}
`,
  },
]

/**
 * Which keys came, went or changed value, so a run says what SC did rather
 * than just that something moved.
 */
function describe(
  before: Record<string, unknown>,
  after: Record<string, unknown>
) {
  const str = (v: unknown) => JSON.stringify(v)
  const added = Object.keys(after).filter(k => !(k in before))
  const removed = Object.keys(before).filter(k => !(k in after))
  const changed = Object.keys(after).filter(
    k => k in before && str(before[k]) !== str(after[k])
  )
  return { added, removed, changed }
}

/**
 * What the file holds now, by importing it rather than reading the source -
 * node strips the types for us, and a regex over an object literal full of
 * quotes and diacritics is asking for trouble
 */
async function readExisting(file: string, name: string) {
  try {
    const mod = await import(join(CONSTANTS_DIR, file))
    return (mod[name] ?? {}) as Record<string, unknown>
  } catch {
    return {}
  }
}

/** Written the way prettier would, so a no-op run really is one */
async function formatted(source: string, filepath: string) {
  const config = await resolveConfig(filepath)
  return format(source, { ...config, filepath })
}

console.log('Syncing constants that mirror a SuttaCentral endpoint\n')

let changedFiles = 0

for (const c of CONSTANTS) {
  process.stdout.write(`${c.file}: `)

  let data: Record<string, unknown>
  try {
    const res = await fetch(c.url)
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    data = c.pick(await res.json())
  } catch (err) {
    console.log(`fetch failed (${(err as Error).message}), left alone`)
    continue
  }

  if (Object.keys(data).length === 0) {
    console.log('api returned nothing, left alone')
    continue
  }

  const name = c.file === 'expansion.ts' ? 'expansionData' : 'referenceEditions'
  const before = await readExisting(c.file, name)
  const path = join(CONSTANTS_DIR, c.file)
  const next = await formatted(c.render(data as any), path)
  const current = await readFile(path, 'utf-8').catch(() => '')

  if (current === next) {
    console.log(`${Object.keys(data).length} entries, unchanged`)
    continue
  }

  await writeFile(path, next)
  changedFiles++

  const { added, removed, changed } = describe(before, data)
  const parts = [
    added.length && `+${added.length} ${added.join(' ')}`,
    removed.length && `-${removed.length} ${removed.join(' ')}`,
    changed.length && `~${changed.length} ${changed.join(' ')}`,
  ].filter(Boolean)
  console.log(
    `${Object.keys(data).length} entries, written` +
      (parts.length ? ` — ${parts.join(', ')}` : ' (formatting only)')
  )
}

console.log(
  changedFiles ? '\nReview changes: git diff src/constants' : '\nNothing to do.'
)
